name: Branch Name

on:
 push:
    branches:
        - '*'   
jobs:
    branch-name:
        env: 
            BRANCH_NAME: ${{ github.ref }}
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Repository
          uses: actions/checkout@v2  

        - name: Display Branch Name
         
          run: echo "Current Branch $BRANCH_NAME"


