name: Branch Name

on:
 push:
    branches:
        - '*'   
env: 
  BRANCH_NAME: ${{ github.ref }}        
jobs:
    branch-name:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Repository
          uses: actions/checkout@v2  

        - name: Display Branch Name
         
          run: echo "Current Branch $BRANCH_NAME"


